name: "khadem_app"
description: A new Khadem project.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  khadem: 
   path: ../
dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.6
