name: "khadem"
description: "A modern Dart backend framework with CLI tools, ORM, authentication, and caching for scalable web applications."
version: 1.1.1-beta
homepage: "https://github.com/khedrmahmoud/khadem"
documentation: "https://khadem-framework.github.io/khadem-docs/"
repository: https://github.com/khedrmahmoud/khadem
issue_tracker: https://github.com/khedrmahmoud/khadem/issues
license: Apache-2.0
release_date: "2025-09-19"
status: "beta"

topics:
  - web-framework
  - backend
  - server
  - api
  - database

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  mime: ^2.0.0
  mysql1: ^0.20.0
  redis: ^4.0.0
  glob: ^2.1.3
  dart_jsonwebtoken: ^3.2.0
  intl: ^0.20.2  
  timezone: ^0.10.1
  uuid: ^4.5.1
  recase: ^4.1.0
  package_config: ^2.2.0
  vm_service: ^15.0.0
  watcher: ^1.1.3
  yaml: ^3.1.3
  yaml_edit: ^2.2.2
  archive: ^4.0.0
  crypto: ^3.0.3
  path: ^1.9.0
  http: ^1.2.0

dev_dependencies:
  very_good_analysis: ^5.1.0
  test: ^1.24.0
  mockito: ^5.5.0
  build_runner: ^2.4.6
  coverage: ^1.15.0
  lints: ^6.0.0
 

executables:
  khadem: